### ISSUE TITLE
kernel boot parameters out of date

### ISSUE THREAD

**Issue by qoijjj** [divestedcg/Brace#3]
The following parameters are no longer recommended:

`mce=0`: https://github.com/Kicksecure/security-misc/pull/113/files

`slub_debug=FZ`: https://github.com/torvalds/linux/commit/792702911f581f7793962fbeb99d5c3a1b28f4c3

**Comment by SkewedZeppelin** [comment]
Brace doesn't enable slub_debug
mce=0 still has benefit on Debian 11

**Comment by qoijjj** [comment]
Ah, I misread it and didn't see it's commented out :+1:
