### ISSUE TITLE
Can no longer access GNOME system monitor after installing brace

### ISSUE THREAD

**Issue by rollsicecream** [divestedcg/Brace#4]
Hello, 

Since I installed `brace` on my laptop, I can no longer access the system monitor from GNOME. I launched it from the terminal and here's what I got : 

```
glibtop(c=27616): [ERROR] open (/proc/diskstats): Permission non accordée
zsh: IOT instruction (core dumped)  gnome-system-monitor
```

"`Permission non accordée`" means "`Permission denied`" by the way.

I think that could be linked to that config from `/usr/lib/tmpfiles.d/99-brace-proc.conf`: 

`z /proc/diskstats 0400 root root
`

**Comment by SkewedZeppelin** [comment]
Thanks for the report.

This one is a new regression, I can comment the line you mention in next update.

**Comment by rollsicecream** [comment]
>  I can comment the line you mention in next update.

Sure, you can :grinning: 

Thanks for making `brace` by the way :+1:
