### ISSUE TITLE
Cannot install any extensions on Firefox

### ISSUE THREAD

**Issue by rollsicecream** [divestedcg/Brace#5]
Hello, 

I actually noticed after installing Firefox (from Fedora's repo, not Flathub/Flatpak) that I cannot install any extensions whatsoever. I noticed then that Brace blocked installations of all extensions apart from allowed ones like NoScript and Enhanced-h264ify.

Furthermore, I think that could be linked to the "ExtensionsSettings" policies visible from line 31 to 36 in : 

https://github.com/divestedcg/Brace/blob/master/brace/usr/lib/firefox/distribution/policies.json

Thank you for fixing that.

**Comment by SkewedZeppelin** [comment]
This is fully intended.

Extensions are a hazard to users.

**Comment by rollsicecream** [comment]
That's totally fair!
