### ISSUE TITLE
KDE Notifications and Clip History broken on restart

### ISSUE THREAD

**Issue by lucasmz-dev** [divestedcg/Brace#7]
file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/main.qml: Operação não permitida

file:///usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/main.qml: Operação não permitida

"Operation not allowed" *

**Comment by SkewedZeppelin** [comment]
did you setup fapolicyd? it can cause blocks like that, not all files get exempted correctly by the filter.

**Comment by lucasmz-dev** [comment]
Oh yep. I guess don't run that then?

**Comment by SkewedZeppelin** [comment]
you can add an exception, eg.:

```
fapolicyd-cli --file add /usr/share/gnome-shell/ --trust-file gnome-shell
fapolicyd-cli --update
```
