### ISSUE TITLE
Connection breaks on restart

### ISSUE THREAD

**Issue by lucasmz-dev** [divestedcg/Brace#8]
My connection is broken after turning on my PC, but is fixed by simply disconnecting and connecting again.

**Comment by lucasmz-dev** [comment]
Ok, happening again; notably youtube.com gives me SEC_ERROR_OCSP_SERVER_ERROR.
But otherwise things somewhat work?

**Comment by SkewedZeppelin** [comment]
> SEC_ERROR_OCSP_SERVER_ERROR

this can be unrelated
same as Mull: https://divestos.org/pages/broken#mull
> Mull has strict certificate revocation checks. The CA revocation servers are frequently down/blocked/inaccessible and will result in a "Secure Connection Failed" error. Navigate to about:config and change security.OCSP.require to false, this is however a security and privacy risk.

**Comment by lucasmz-dev** [comment]
Something was off though (sorry, it was significantly broken that I just ended up doing a reinstall)

This only happens with Brace when it is having that issue, and the connection sometimes works, sometimes doesn't. It's very weird. Reconnecting solves it, but it's weird overall. Not sure if it can be my ISP's DNS.
